[tools]
cosign = "3.0.4"
"pipx:yamllint" = "1.38.0"
actionlint = "1.7.10"
shellcheck = "0.11.0"

[env]
IMAGE_NAME = "ghcr.io/clemak27/kinokite"
IMAGE_TAG = "latest"

[tasks.lint]
run = """
yamllint .
actionlint
shellcheck build.sh
shellcheck plasma.sh
"""

[tasks.build-image]
run = """
docker build -t ${IMAGE_NAME}:${IMAGE_TAG} . -f ./Containerfile.kinokite
"""

[tasks.build-image-deck]
run = """
docker build -t ${IMAGE_NAME}-deck:${IMAGE_TAG} . -f ./Containerfile.deck
"""
